FROM node:alpine

WORKDIR /pds
COPY ./pds.env /pds

# WORKDIR /opt
# RUN apk add --no-cache git
# RUN apk add --no-cache curl
# RUN apk add --no-cache wget
# RUN apk add --no-cache openssh
# RUN git clone https://github.com/bluesky-social/pds.git /opt/pds-tools
# COPY /opt/pds-tools/pdsadmin /opt/pdsadmin
# WORKDIR /opt/pdsadmin