[package]
name = "registry"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rocket = "0.5.1"
surrealdb-migrations = "1.5.0"
surrealdb = "1.5.3"
thiserror = "1.0.61"
surreal_bb8 = "0.1.0"
