[default]
port = 3984

[default.auth]
secret_key = ""

[default.service]
public_url = "example.com"
did = "did:web:example.com"
secret_key = ""

[default.database]
url = "postgresql://example:example@localhost/registry"