[default]
port = 3984

[default.surreal]
host = "ws://localhost"
port = 8000
user = "example"
password = "example"
database = "registry"
namespace = "example.com"

[default.auth]
secret_key = ""

[default.service]
public_url = "example.com"